import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/layout/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-guaruja">
        <div className="relative h-auto w-full overflow-x-hidden scrollbar-hide overflow-y-auto">
          <Navigation />
          {children}
        </div>
      </body>
    </html>
  );
}
