import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/layout/Navigation";
import SideBar from "@/components/layout/SideBar";
import FooterNav from "@/components/layout/FooterNav";
import { headers } from "next/headers";

import { cookieToInitialState } from "wagmi";

import { config } from "@/config";
import Web3ModalProvider from "@/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body className="font-guaruja">
        <div className="flex w-full h-auto relative">
          <SideBar />
          <div className="relative w-full h-auto">
            <Navigation />
            <div className="scrollbar-hide overflow-y-auto h-[100vh] w-full overflow-x-hidden pt-20">
              <Web3ModalProvider initialState={initialState}>
                {children}
              </Web3ModalProvider>
            </div>
            <FooterNav />
          </div>
        </div>
      </body>
    </html>
  );
}
